services:
  domain-api:
    build: .
    container_name: domain-checker-api
    restart: unless-stopped
    ports:
      - "8585:8585"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8585
